from .events import FileSystemEventHandler

class Observer:
    def schedule(
        self, event_handler: FileSystemEventHandler, path: str, recursive: bool = False
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def join(self) -> None: ...
